wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1645367196
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 2
      - 3
      - 5
