wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1644795222
    t:
      1:
      - 5
      - 6
      2:
      - 5
      - 6
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 2
      - 3
      - 5
booster:
  desc: null
  value: gbtree
learning_rate:
  desc: null
  value: 0.2
max_depth:
  desc: null
  value: 12
seed:
  desc: null
  value: 117
subsample:
  desc: null
  value: 0.3
test_size:
  desc: null
  value: 0.33
