wandb_version: 1

_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_items:
  desc: null
  value:
    _wandb: {}
    architecture: ResNet
    batch_size: 128
    epochs: 100
    learning_rate: 5.88e-05
_locked:
  desc: null
  value: {}
_settings:
  desc: null
  value: '<Settings {''_args'': [''-f'', ''C:\\Users\\zhuan\\AppData\\Roaming\\jupyter\\runtime\\kernel-4b0b7174-1ee2-4d18-be80-771dbaf2e020.json''],
    ''_cli_only_mode'': None, ''_config_dict'': None, ''_cuda'': None, ''_debug_log'':
    None, ''_disable_meta'': None, ''_disable_stats'': None, ''_disable_viewer'':
    None, ''_except_exit'': True, ''_executable'': ''D:\\Users\\zhuan\\anaconda3\\envs\\ml\\python.exe'',
    ''_internal_check_process'': 8, ''_internal_queue_timeout'': 2, ''_jupyter_name'':
    None, ''_jupyter_path'': None, ''_jupyter_root'': None, ''_os'': ''Windows-10-10.0.22000-SP0'',
    ''_python'': ''3.9.7'', ''_require_service'': None, ''_runqueue_item_id'': None,
    ''_save_requirements'': True, ''_service_transport'': None, ''_start_datetime'':
    datetime.datetime(2022, 2, 21, 20, 32, 7, 149524), ''_start_time'': 1645493527.1495242,
    ''_tmp_code_dir'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground
    Series - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\tmp\\code'', ''_unsaved_keys'':
    None, ''allow_val_change'': None, ''anonymous'': None, ''api_key'': ''***REDACTED***'',
    ''base_url'': ''https://api.wandb.ai'', ''code_dir'': None, ''config_paths'':
    None, ''console'': ''auto'', ''disable_code'': None, ''disable_git'': False, ''disabled'':
    False, ''docker'': None, ''email'': ''zhuang.eddie@gmail.com'', ''entity'': None,
    ''files_dir'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series
    - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\files'', ''force'': None, ''git_remote'':
    ''origin'', ''heartbeat_seconds'': 30, ''host'': ''DESKTOP-6RO9CFE'', ''ignore_globs'':
    (), ''label_disable'': None, ''launch'': None, ''launch_config_path'': None, ''log_dir'':
    ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\logs'',
    ''log_internal'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series
    - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\logs\\debug-internal.log'', ''log_symlink_internal'':
    ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series - Feb 2022\\wandb\\debug-internal.log'',
    ''log_symlink_user'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground
    Series - Feb 2022\\wandb\\debug.log'', ''log_user'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular
    Playground Series - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\logs\\debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    None, ''problem'': ''fatal'', ''program'': ''<python with no main file>'', ''program_relpath'':
    None, ''project'': ''tab-playground-feb-2022'', ''quiet'': None, ''reinit'': None,
    ''relogin'': None, ''resume'': None, ''resume_fname'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular
    Playground Series - Feb 2022\\wandb\\wandb-resume.json'', ''root_dir'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular
    Playground Series - Feb 2022'', ''run_group'': None, ''run_id'': ''39797e8w'',
    ''run_job_type'': None, ''run_name'': None, ''run_notes'': None, ''run_tags'':
    None, ''sagemaker_disable'': None, ''save_code'': True, ''settings_system'': ''C:\\Users\\zhuan\\.config\\wandb\\settings'',
    ''settings_workspace'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground
    Series - Feb 2022\\wandb\\settings'', ''show_colors'': None, ''show_emoji'': None,
    ''show_errors'': True, ''show_info'': True, ''show_warnings'': True, ''silent'':
    False, ''start_method'': None, ''strict'': None, ''summary_errors'': None, ''summary_warnings'':
    5, ''sweep_id'': None, ''sweep_param_path'': None, ''symlink'': False, ''sync_dir'':
    ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series - Feb 2022\\wandb\\run-20220221_203207-39797e8w'',
    ''sync_file'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series
    - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\run-39797e8w.wandb'', ''sync_symlink_latest'':
    ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular Playground Series - Feb 2022\\wandb\\latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''tmp_dir'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular
    Playground Series - Feb 2022\\wandb\\run-20220221_203207-39797e8w\\tmp'', ''username'':
    ''zhuan'', ''_console'': <SettingsConsole.WRAP: 1>, ''_jupyter'': True, ''_kaggle'':
    True, ''_noop'': False, ''_offline'': False, ''_quiet'': None, ''_show_info'':
    True, ''_show_warnings'': True, ''_show_errors'': True, ''_silent'': False, ''_strict'':
    None, ''_windows'': True, ''is_local'': False, ''run_mode'': ''run'', ''timespec'':
    ''20220221_203207'', ''wandb_dir'': ''D:\\GeekyStuff\\Python\\Kaggle-Stuff\\Tabular
    Playground Series - Feb 2022\\wandb\\''}>'
_users:
  desc: null
  value: {}
_users_cnt:
  desc: null
  value: 0
_users_inv:
  desc: null
  value: {}
_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1645493599
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 2
      - 3
      - 5
