wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1645497592
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      - 16
      4: 3.9.7
      5: 0.12.10
      8:
      - 1
      - 2
      - 3
      - 5
architecture:
  desc: null
  value: ResNet
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 5.88e-05
